Add -t option for optional installs
Test Plan:
run with `-t` option
//Depends on D382//

Reviewers: michael.akinde, #testdev, #jvmdev, yogesh.kharode

Reviewed By: #jvmdev, yogesh.kharode

Subscribers: yogesh.kharode

Differential Revision: https://phabricator.elhub.cloud/D392

diff --git a/scripts/dev-tools b/scripts/dev-tools
--- a/scripts/dev-tools
+++ b/scripts/dev-tools
@@ -1,10 +1,11 @@
 #!/bin/bash
 #
 # ARG_POSITIONAL_SINGLE([action],[Valid actions are 'install' and 'upgrade'.],[])
+# ARG_OPTIONAL_SINGLE([type],[t],[Valid types are: 'full', 'adr', 'arcanist', 'checkstyle', 'detekt'],[full])
 # ARG_HELP([Utility script to install and upgrade client-side dev-tools extensions and tools.])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
-### START OF CODE GENERATED BY Argbash v2.8.1 one line above ###
+### START OF CODE GENERATED BY Argbash v2.9.0 one line above ###
 # Argbash is a bash code generator used to get arguments parsing right.
 # Argbash is FREE SOFTWARE, see https://argbash.io for more info
 # Generated online by https://argbash.io/generate
@@ -12,17 +13,16 @@
 
 die()
 {
-  local _ret=$2
-  test -n "$_ret" || _ret=1
-  test "$_PRINT_HELP" = yes && print_help >&2
+  local _ret="${2:-1}"
+  test "${_PRINT_HELP:-no}" = yes && print_help >&2
   echo "$1" >&2
-  exit ${_ret}
+  exit "${_ret}"
 }
 
 
 begins_with_short_option()
 {
-  local first_option all_short_options='h'
+  local first_option all_short_options='th'
   first_option="${1:0:1}"
   test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
@@ -30,13 +30,15 @@ begins_with_short_option()
 # THE DEFAULTS INITIALIZATION - POSITIONALS
 _positionals=()
 # THE DEFAULTS INITIALIZATION - OPTIONALS
+_arg_type="full"
 
 
 print_help()
 {
-  printf '%s\n' "Utility script to install and upgrade client-side phabricator extensions and tools."
-  printf 'Usage: %s [-h|--help] <action>\n' "$0"
+  printf '%s\n' "Utility script to install and upgrade client-side dev-tools extensions and tools."
+  printf 'Usage: %s [-t|--type <arg>] [-h|--help] <action>\n' "$0"
   printf '\t%s\n' "<action>: Valid actions are 'install' and 'upgrade'."
+  printf '\t%s\n' "-t, --type: Valid types are: 'full', 'adr', 'arcanist', 'checkstyle', 'detekt' (default: 'full')"
   printf '\t%s\n' "-h, --help: Prints help"
 }
 
@@ -48,6 +50,17 @@ parse_commandline()
   do
     _key="$1"
     case "$_key" in
+      -t|--type)
+        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+        _arg_type="$2"
+        shift
+        ;;
+      --type=*)
+        _arg_type="${_key##--type=}"
+        ;;
+      -t*)
+        _arg_type="${_key##-t}"
+        ;;
       -h|--help)
         print_help
         exit 0
@@ -162,7 +175,7 @@ build_checkstyle()
   cd "$DEV_HOME"/"$REPO_CHECKSTYLE" || exit 1
   cp -r "$DEV_HOME"/"$REPO_MVNW"/.mvn .
   cp "$DEV_HOME"/"$REPO_MVNW"/mvnw* .
-  ./mvnw -DskipTests -P assembly -q clean package
+  ./mvnw -U -DskipTests -P assembly -q clean package
   cd "$DEV_HOME" || exit 1
   rm $REPO_CHECKSTYLE/target/*tests.jar
   mv $(ls -rt $REPO_CHECKSTYLE/target/*-all.jar | tail -n1) lib/checkstyle.jar
@@ -217,11 +230,28 @@ ensure_detekt()
 if [ "$_arg_action" == "install" ] || [ "$_arg_action" == "upgrade" ]; then
   cd "$SCRIPT_PATH"/.. || exit 1
   git pull
-  ensure_mvnw
-  ensure_adrj
-  ensure_arcanist
-  ensure_checkstyle
-  ensure_detekt
+
+  if [ "$_arg_type" == "full" ]; then
+    ensure_mvnw
+    ensure_adrj
+    ensure_arcanist
+    ensure_checkstyle
+    ensure_detekt
+  elif [[ "$_arg_type" == "adr" ]]; then
+    ensure_adrj
+  elif [[ "$_arg_type" == "arcanist" ]]; then
+    ensure_arcanist
+  elif [[ "$_arg_type" == "checkstyle" ]]; then
+    ensure_mvnw
+    ensure_checkstyle
+  elif [[ "$_arg_type" == "detekt" ]]; then
+    ensure_detekt
+  else
+    echo "Incorrect argument for --type option."
+    print_help
+    exit 1
+  fi
+
   cd "$ORIGIN_PATH" || exit 1
 else
   print_help
