Enable make-release from past commits
Summary:
We don't always want to make a release from the tip of `origin/master`,
therefore added extra optional argument to use as "source" for the release.

Additionally added some small error handling.

Test Plan: run tests with `--test`

Reviewers: michael.akinde, #jvmdev, #jsdev, #servicesdev, #coredev

Reviewed By: michael.akinde, #jvmdev, #jsdev

Differential Revision: https://phabricator.elhub.cloud/D530

diff --git a/scripts/make-release b/scripts/make-release
--- a/scripts/make-release
+++ b/scripts/make-release
@@ -1,6 +1,7 @@
 #!/bin/bash
 #
 # ARG_POSITIONAL_SINGLE([release_name],[Release name. Allowed: v<major>.<minor>.<patch>, v<major>.<minor>.<patch>-rc.<num>, v<major>.<minor>.<patch>-alpha.<num>],[])
+# ARG_POSITIONAL_SINGLE([release_source],[Release source: a git tag, git branch name, or a git commit hash.],[origin/master])
 # ARG_OPTIONAL_BOOLEAN([test],[],[Runs a test])
 # ARG_HELP([Simplifies creation of release branches.])
 # ARGBASH_GO()
@@ -29,6 +30,7 @@ begins_with_short_option()
 
 # THE DEFAULTS INITIALIZATION - POSITIONALS
 _positionals=()
+_arg_release_source="origin/master"
 # THE DEFAULTS INITIALIZATION - OPTIONALS
 _arg_test="off"
 
@@ -36,8 +38,9 @@ _arg_test="off"
 print_help()
 {
   printf '%s\n' "Simplifies creation of release branches."
-  printf 'Usage: %s [--(no-)test] [-h|--help] <release_name>\n' "$0"
+  printf 'Usage: %s [--(no-)test] [-h|--help] <release_name> [<release_source>]\n' "$0"
   printf '\t%s\n' "<release_name>: Release name. Allowed: v<major>.<minor>.<patch>, v<major>.<minor>.<patch>-rc.<num>, v<major>.<minor>.<patch>-alpha.<num>"
+  printf '\t%s\n' "<release_source>: Release source: a tag, git branch name, or a git commit hash. (default: 'origin/master')"
   printf '\t%s\n' "--test, --no-test: Runs a test (off by default)"
   printf '\t%s\n' "-h, --help: Prints help"
 }
@@ -76,15 +79,15 @@ parse_commandline()
 handle_passed_args_count()
 {
   local _required_args_string="'release_name'"
-  test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
-  test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
+  test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require between 1 and 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+  test "${_positionals_count}" -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect between 1 and 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
 }
 
 
 assign_positional_args()
 {
   local _positional_name _shift_for=$1
-  _positional_names="_arg_release_name "
+  _positional_names="_arg_release_name _arg_release_source "
 
   shift "$_shift_for"
   for _positional_name in ${_positional_names}
@@ -104,6 +107,13 @@ assign_positional_args 1 "${_positionals[@]}"
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
 
+# exit when something fails
+set -eE
+# keep track of the last executed command
+trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
+# echo an error message before exiting
+trap 'printf "\e[31m%s: %s\e[m\n" "\"${last_command}\" failed with exit code" $?.' ERR
+
 release_regex='^v\([0-9]\+\.\?\)\{3\}\(\(-rc\|-alpha\)\.[0-9]\+\)\?$'
 
 if echo $_arg_release_name | grep -q $release_regex; then
@@ -113,9 +123,11 @@ if echo $_arg_release_name | grep -q $release_regex; then
   fi
 
   git fetch # update remote tracking branches
-  git branch $_arg_release_name origin/master # create release branch from origin/master
 
-  read -p "push $_arg_release_name to origin, do you want to continue? [y/N]: " _push
+  echo "Create release '$_arg_release_name' from '$_arg_release_source'"
+  git branch $_arg_release_name $_arg_release_source # create release branch from a git source
+
+  read -p "Push release '$_arg_release_name' to origin, do you want to continue? [y/N]: " _push
 
   if [[ $_push == "y" ]]; then
     git push origin $_arg_release_name # push release branch to remote
