Refactor arc-init related tasks and add templates
Summary:
Move repo-based templates to separate dir for better readability.

Refactor tasks for setting up templates.

Add extra templates for ansible.

Fix 'copy-git-hooks' script.

Test Plan: install dev tools; run `arc init` in a temp dir; check the dir contents

Reviewers: O5 elhub/devtools, michael.akinde

Reviewed By: O5 elhub/devtools, michael.akinde

Differential Revision: https://phabricator.elhub.cloud/D985

diff --git a/roles/arcanist_workstation/templates/arc-init.sh.j2 b/roles/arcanist_workstation/templates/arc-init.sh.j2
--- a/roles/arcanist_workstation/templates/arc-init.sh.j2
+++ b/roles/arcanist_workstation/templates/arc-init.sh.j2
@@ -1,6 +1,7 @@
 #!/bin/bash
 #
 # ARG_POSITIONAL_SINGLE([action],[Valid actions are 'gradle', 'maven' and 'none'.],[])
+# ARG_OPTIONAL_SINGLE([extras],[],[A coma-separated list of additional config files. Valid values are 'ansible'.],[])
 # ARG_HELP([Utility script to initialize a code directory for arcanist.])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
@@ -12,80 +13,90 @@
 
 die()
 {
-    local _ret="${2:-1}"
-    test "${_PRINT_HELP:-no}" = yes && print_help >&2
-    echo "$1" >&2
-    exit "${_ret}"
+  local _ret="${2:-1}"
+  test "${_PRINT_HELP:-no}" = yes && print_help >&2
+  echo "$1" >&2
+  exit "${_ret}"
 }
 
 
 begins_with_short_option()
 {
-    local first_option all_short_options='h'
-    first_option="${1:0:1}"
-    test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+  local first_option all_short_options='h'
+  first_option="${1:0:1}"
+  test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
 
 # THE DEFAULTS INITIALIZATION - POSITIONALS
 _positionals=()
 # THE DEFAULTS INITIALIZATION - OPTIONALS
+_arg_extras=
 
 
 print_help()
 {
-    printf '%s\n' "Utility script to initialize a code directory for arcanist."
-    printf 'Usage: %s [-h|--help] <action>\n' "$0"
-    printf '\t%s\n' "<action>: Valid actions are 'gradle', 'maven' and 'none'."
-    printf '\t%s\n' "-h, --help: Prints help"
+  printf '%s\n' "Utility script to initialize a code directory for arcanist."
+  printf 'Usage: %s [--extras <arg>] [-h|--help] <action>\n' "$0"
+  printf '\t%s\n' "<action>: Valid actions are 'gradle', 'maven' and 'none'."
+  printf '\t%s\n' "--extras: A coma-separated list of additional config files. Valid values are 'ansible'. (no default)"
+  printf '\t%s\n' "-h, --help: Prints help"
 }
 
 
 parse_commandline()
 {
-    _positionals_count=0
-    while test $# -gt 0
-    do
-        _key="$1"
-        case "$_key" in
-            -h|--help)
-                print_help
-                exit 0
-                ;;
-            -h*)
-                print_help
-                exit 0
-                ;;
-            *)
-                _last_positional="$1"
-                _positionals+=("$_last_positional")
-                _positionals_count=$((_positionals_count + 1))
-                ;;
-        esac
+  _positionals_count=0
+  while test $# -gt 0
+  do
+    _key="$1"
+    case "$_key" in
+      --extras)
+        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+        _arg_extras="$2"
         shift
-    done
+        ;;
+      --extras=*)
+        _arg_extras="${_key##--extras=}"
+        ;;
+      -h|--help)
+        print_help
+        exit 0
+        ;;
+      -h*)
+        print_help
+        exit 0
+        ;;
+      *)
+        _last_positional="$1"
+        _positionals+=("$_last_positional")
+        _positionals_count=$((_positionals_count + 1))
+        ;;
+    esac
+    shift
+  done
 }
 
 
 handle_passed_args_count()
 {
-    local _required_args_string="'action'"
-    test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
-    test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
+  local _required_args_string="'action'"
+  test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+  test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
 }
 
 
 assign_positional_args()
 {
-    local _positional_name _shift_for=$1
-    _positional_names="_arg_action "
+  local _positional_name _shift_for=$1
+  _positional_names="_arg_action "
 
-    shift "$_shift_for"
-    for _positional_name in ${_positional_names}
-    do
-        test $# -gt 0 || break
-        eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
-        shift
-    done
+  shift "$_shift_for"
+  for _positional_name in ${_positional_names}
+  do
+    test $# -gt 0 || break
+    eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
+    shift
+  done
 }
 
 parse_commandline "$@"
@@ -96,22 +107,35 @@ assign_positional_args 1 "${_positionals[@]}"
 
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
-TEMPLATE_PATH={{ devtools_path}}/templates
+set -eE
 
-if [ "$_arg_action" == "gradle" ]; then
-    cp $TEMPLATE_PATH/.arcconfig-gradle .arcconfig
-elif [[ "$_arg_action" == "maven" ]]; then
-    cp $TEMPLATE_PATH/.arcconfig-maven .arcconfig
-elif [[ "$_arg_action" == "none" ]]; then
-    cp $TEMPLATE_PATH/.arcconfig .arcconfig
-else
+TEMPLATE_PATH={{ devtools_path}}/templates/repo
+
+if ! echo "$_arg_action" | egrep '(gradle|maven|none)' >/dev/null; then
     print_help
     exit 1;
 fi
-cp $TEMPLATE_PATH/.arclint .
-cp $TEMPLATE_PATH/.gitattributes .
-cp $TEMPLATE_PATH/.gitignore .
-cp $TEMPLATE_PATH/CONTRIBUTING.md .
-cp $TEMPLATE_PATH/README.md .
+
+cp "${TEMPLATE_PATH}/arcconfig-${_arg_action}-template" ./.arcconfig
+cp $TEMPLATE_PATH/arclint-template ./.arclint
+cp $TEMPLATE_PATH/CONTRIBUTING-template.md ./CONTRIBUTING.md
+cp $TEMPLATE_PATH/gitattributes-template ./.gitattributes
+cp $TEMPLATE_PATH/gitignore-template ./.gitignore
+cp $TEMPLATE_PATH/Makefile-template ./Makefile
+cp $TEMPLATE_PATH/README-template.md ./README.md
+
+IFS=',' read -ra EXTRAS <<< "$_arg_extras"
+unset IFS
+
+if [[ "${EXTRAS[@]}" =~ "ansible" ]]; then
+  cp $TEMPLATE_PATH/yamllint-template ./.yamllint
+  cp $TEMPLATE_PATH/ansible-lint-template ./.ansible-lint
+fi
+
+if [[ $(git rev-parse --is-inside-work-tree) == "true" ]]; then
+    git init
+fi
+
+make init
 
 # ] <-- needed because of Argbash
